name: discovery-server CI/CD

on:
  pull_request:
    branches: production
    paths:
      - 'discovery-server/**'
defaults: 
  run: 
    working-directory: discovery-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    
    - name: Build and test
      run: ./gradlew build --info

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Build Docker image
      run: docker build -t registry.heroku.com/${{ secrets.DISCOVERY-SERVER_HEROKU_APP }}/web:latest .

    - name: Docker image info
      run: docker images
  
    - name: Login to container registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login

    - name: Push Docker image
      run: docker push registry.heroku.com/${{ secrets.DISCOVERY-SERVER_HEROKU_APP }}/web

    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release -a ${{ secrets.DISCOVERY-SERVER_HEROKU_APP }} web